apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lrc-backend.fullname" . }}
  labels:
    {{- include "lrc-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lrc-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lrc-backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: lrc-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
