{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lrc-backend.serviceAccountName" . }}
  labels:
    {{- include "lrc-backend.labels" . | nindent 4 }}
{{- end }}
